apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  serviceName: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - name: app
          image: {{ .Values.images.app }}
          #command: ['sh', '-c', 'echo The app is running! && sleep 10000']
          ports:
            - containerPort: 80
          env:
            {{- range .Values.env }}
            {{- if contains "app" .selector }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            - name: REPOSITORY_URL
              value: {{ .Values.repositories.web.url }} 
            - name: REPOSITORY_BRANCH
              value: {{ .Values.repositories.web.branch }} 
            - name: GIT_USER_EMAIL
              value: {{ .Values.repositories.web.gitUserEmail }} 
            - name: GIT_USER_NAME
              value: {{ .Values.repositories.web.gitUserName }}               
          volumeMounts:
            {{- if hasKey .Values.storage "app" }}
            - name: app-mount
              mountPath: /app
            {{- end }}
            {{- if hasKey .Values.storage "rootpersist" }}
            - name: root-mount
              mountPath: /root-persist
            {{- end }}
            - name: ssh-keys
              mountPath: /etc/ssh/internal_ssh_host_rsa.pub
              subPath: internal_ssh_host_rsa.pub
      volumes:
        {{- if hasKey .Values.storage "app" }}
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.app.hostPath }}
        {{- end }}
        {{- if hasKey .Values.storage "rootpersist" }}
        - name: root-mount
          hostPath:
            path: {{ .Values.storage.rootpersist.hostPath }}
        {{- end }}
        - name: ssh-keys
          secret:
            secretName: ssh-keys

        
